import PDFDocument from 'pdfkit';
import prisma from '../database/prisma.js';

export async function generateAuditReport(platformId, startDate, endDate, res) {
  const start = new Date(startDate);
  const end = new Date(endDate);

  // Fetch all data
  const [platform, haccpChecks, cleaningTasks, inspections, receivingChecks] = await Promise.all([
    prisma.platform.findUnique({ where: { id: platformId } }),
    prisma.haccpCheck.findMany({
      where: { platform_id: platformId, checked_at: { gte: start, lte: end } },
      include: { point: true, checked_by: { select: { full_name: true } } },
      orderBy: { checked_at: 'asc' },
    }),
   prisma.cleaningTask.findMany({
  where: { platform_id: platformId },
  orderBy: { name: 'asc' },
}),
    prisma.inspection.findMany({
  where: { platform_id: platformId, conducted_at: { gte: start, lte: end } },
  include: { inspector: { select: { full_name: true } } },
  orderBy: { conducted_at: 'asc' },
}),
    prisma.receivingCheck.findMany({
      where: { platform_id: platformId, checked_at: { gte: start, lte: end } },
      include: { checked_by: { select: { full_name: true } } },
      orderBy: { checked_at: 'asc' },
    }),
  ]);

  // Stats
  const totalChecks = haccpChecks.length;
  const passChecks = haccpChecks.filter(c => c.result === 'PASS').length;
  const failChecks = haccpChecks.filter(c => c.result === 'FAIL').length;
  const warnChecks = haccpChecks.filter(c => c.result === 'WARNING').length;
  const complianceRate = totalChecks > 0 ? ((passChecks / totalChecks) * 100).toFixed(1) : 0;
  const avgInspectionScore = inspections.length > 0
    ? (inspections.reduce((s, i) => s + Number(i.score || 0), 0) / inspections.length).toFixed(1)
    : 'N/A';

  // Create PDF
  const doc = new PDFDocument({ margin: 50, size: 'A4' });

  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader('Content-Disposition', `attachment; filename="audit-report-${startDate}-to-${endDate}.pdf"`);
  doc.pipe(res);

  // Helper functions
  const drawLine = () => {
    doc.moveTo(50, doc.y).lineTo(545, doc.y).strokeColor('#e2e8f0').stroke();
    doc.moveDown(0.5);
  };

  const sectionTitle = (title) => {
    doc.moveDown(1);
    doc.rect(50, doc.y, 495, 24).fill('#1e3a5f');
    doc.fillColor('#ffffff').fontSize(11).font('Helvetica-Bold')
      .text(title, 58, doc.y - 18);
    doc.fillColor('#000000');
    doc.moveDown(0.8);
  };

  const row = (label, value, highlight = false) => {
    const y = doc.y;
    if (highlight) doc.rect(50, y - 2, 495, 18).fill('#f8fafc');
    doc.fillColor('#64748b').fontSize(9).font('Helvetica').text(label, 58, y, { width: 200 });
    doc.fillColor('#0f172a').fontSize(9).font('Helvetica-Bold').text(String(value), 270, y, { width: 270 });
    doc.moveDown(0.6);
  };

  // ── HEADER ──
  doc.rect(0, 0, 595, 80).fill('#0f172a');
  doc.fillColor('#f97316').fontSize(24).font('Helvetica-Bold').text('CAMP BOSS', 50, 20);
  doc.fillColor('#94a3b8').fontSize(10).font('Helvetica').text('Offshore Camp Management System', 50, 48);
  doc.fillColor('#ffffff').fontSize(14).font('Helvetica-Bold').text('HACCP & FOOD SAFETY AUDIT REPORT', 50, 62, { align: 'right' });
  doc.moveDown(3);

  // ── REPORT INFO ──
  doc.fillColor('#0f172a').fontSize(10).font('Helvetica-Bold').text('REPORT DETAILS', 50);
  drawLine();
  row('Platform', platform?.name || 'All Platforms');
  row('Report Period', `${start.toLocaleDateString('en-GB')} to ${end.toLocaleDateString('en-GB')}`, true);
  row('Generated On', new Date().toLocaleString('en-GB'));
  row('Generated By', 'Camp Boss System');

  // ── EXECUTIVE SUMMARY ──
  sectionTitle('EXECUTIVE SUMMARY');
  row('Total HACCP Checks', totalChecks);
  row('Passed', `${passChecks} (${complianceRate}%)`, true);
  row('Warnings', warnChecks);
  row('Failures', failChecks, true);
  row('Compliance Rate', `${complianceRate}%`);
  row('Total Deliveries Received', receivingChecks.length, true);
  row('Kitchen Inspections Conducted', inspections.length);
  row('Average Inspection Score', `${avgInspectionScore}%`, true);

  // ── HACCP TEMPERATURE LOG ──
  sectionTitle('HACCP TEMPERATURE LOG');

  if (haccpChecks.length === 0) {
    doc.fillColor('#64748b').fontSize(9).text('No HACCP checks recorded for this period.', 58);
    doc.moveDown(0.5);
  } else {
    // Table header
    const tableTop = doc.y;
    doc.rect(50, tableTop, 495, 18).fill('#e2e8f0');
    doc.fillColor('#0f172a').fontSize(8).font('Helvetica-Bold');
    doc.text('Date/Time', 58, tableTop + 4, { width: 100 });
    doc.text('Monitoring Point', 158, tableTop + 4, { width: 140 });
    doc.text('Temp (°C)', 298, tableTop + 4, { width: 60 });
    doc.text('Result', 358, tableTop + 4, { width: 60 });
    doc.text('Checked By', 418, tableTop + 4, { width: 120 });
    doc.moveDown(1.2);

    haccpChecks.forEach((check, i) => {
      if (doc.y > 720) { doc.addPage(); }
      const rowY = doc.y;
      if (i % 2 === 0) doc.rect(50, rowY - 2, 495, 16).fill('#f8fafc');
      const resultColor = check.result === 'PASS' ? '#10b981' : check.result === 'FAIL' ? '#ef4444' : '#f59e0b';
      doc.fillColor('#334155').fontSize(8).font('Helvetica');
      doc.text(new Date(check.checked_at).toLocaleString('en-GB'), 58, rowY, { width: 100 });
      doc.text(check.point?.name || '—', 158, rowY, { width: 140 });
      doc.text(`${check.temperature}°C`, 298, rowY, { width: 60 });
      doc.fillColor(resultColor).font('Helvetica-Bold').text(check.result, 358, rowY, { width: 60 });
      doc.fillColor('#334155').font('Helvetica').text(check.checked_by?.full_name || '—', 418, rowY, { width: 120 });
      doc.moveDown(0.8);

      if (check.result === 'FAIL' && check.corrective_action) {
        doc.fillColor('#ef4444').fontSize(7.5).font('Helvetica-Oblique')
          .text(`↳ Corrective Action: ${check.corrective_action}`, 68, doc.y, { width: 470 });
        doc.moveDown(0.5);
      }
    });
  }

  // ── RECEIVING LOG ──
  sectionTitle('DELIVERY RECEIVING LOG');

  if (receivingChecks.length === 0) {
    doc.fillColor('#64748b').fontSize(9).text('No deliveries recorded for this period.', 58);
    doc.moveDown(0.5);
  } else {
    const tableTop = doc.y;
    doc.rect(50, tableTop, 495, 18).fill('#e2e8f0');
    doc.fillColor('#0f172a').fontSize(8).font('Helvetica-Bold');
    doc.text('Date', 58, tableTop + 4, { width: 80 });
    doc.text('Supplier', 138, tableTop + 4, { width: 130 });
    doc.text('Invoice No', 268, tableTop + 4, { width: 100 });
    doc.text('Status', 368, tableTop + 4, { width: 80 });
    doc.text('Received By', 448, tableTop + 4, { width: 100 });
    doc.moveDown(1.2);

    receivingChecks.forEach((rec, i) => {
      if (doc.y > 720) { doc.addPage(); }
      const rowY = doc.y;
      if (i % 2 === 0) doc.rect(50, rowY - 2, 495, 16).fill('#f8fafc');
      const statusColor = rec.status === 'ACCEPTED' ? '#10b981' : rec.status === 'REJECTED' ? '#ef4444' : '#f59e0b';
      doc.fillColor('#334155').fontSize(8).font('Helvetica');
      doc.text(new Date(rec.checked_at).toLocaleDateString('en-GB'), 58, rowY, { width: 80 });
      doc.text(rec.supplier, 138, rowY, { width: 130 });
      doc.text(rec.invoice_no || '—', 268, rowY, { width: 100 });
      doc.fillColor(statusColor).font('Helvetica-Bold').text(rec.status, 368, rowY, { width: 80 });
      doc.fillColor('#334155').font('Helvetica').text(rec.checked_by?.full_name || '—', 448, rowY, { width: 100 });
      doc.moveDown(0.8);
    });
  }

  // ── INSPECTIONS ──
  sectionTitle('KITCHEN INSPECTIONS');

  if (inspections.length === 0) {
    doc.fillColor('#64748b').fontSize(9).text('No inspections recorded for this period.', 58);
    doc.moveDown(0.5);
  } else {
    inspections.forEach((insp, i) => {
      if (doc.y > 720) { doc.addPage(); }
      const scoreColor = Number(insp.score) >= 80 ? '#10b981' : Number(insp.score) >= 60 ? '#f59e0b' : '#ef4444';
      row(`Inspection ${i + 1} — ${new Date(insp.conducted_at).toLocaleDateString('en-GB')}`,
        `Score: ${insp.score}% | Inspector: ${insp.inspector?.full_name || '—'}`, i % 2 === 0);
    });
  }

  // ── FOOTER ──
  doc.moveDown(2);
  drawLine();
  doc.fillColor('#94a3b8').fontSize(8).font('Helvetica')
    .text(`This report was automatically generated by Camp Boss on ${new Date().toLocaleString('en-GB')}. All records are timestamped and tamper-evident.`, 50, doc.y, { align: 'center', width: 495 });

  doc.end();
}